# Generated by Django 3.0.4 on 2020-06-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='blog_image',
            field=models.ImageField(upload_to='profile'),
        ),
    ]
