# Generated by Django 3.0.4 on 2020-06-02 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200602_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='code',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='code_image',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='output',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='output_image',
        ),
        migrations.DeleteModel(
            name='PostDetail',
        ),
    ]
