# Generated by Django 3.0.4 on 2020-06-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200602_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_subjects',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')]),
        ),
    ]
