# Generated by Django 3.0.4 on 2020-05-15 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=120)),
                ('message', models.TextField(max_length=800)),
                ('created_at', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'contactus',
            },
        ),
    ]
