# Generated by Django 3.0.4 on 2020-06-01 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Projects', 'verbose_name_plural': 'Projects'},
        ),
    ]
